# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.

[workspace]
members = [
  "examples/cmd_drivers/build_memory_index",
  "examples/cmd_drivers/build_and_insert_memory_index",
  "examples/cmd_drivers/load_and_insert_memory_index",
  "examples/cmd_drivers/convert_f32_to_bf16",
  "examples/cmd_drivers/search_memory_index",
  #"examples/cmd_drivers/build_disk_index",
  "examples/cmd_drivers/build_and_insert_delete_memory_index",
  "vector",
  "diskann",
  "platform",
  "vector_base64",
  "examples/vector-search-demo/vector-search-demo",
  "examples/dataset-generators/generate_large_dataset",
  "examples/cmd_drivers/build_memory_index",
  "examples/cmd_drivers/build_and_insert_memory_index",
  "examples/cmd_drivers/load_and_insert_memory_index",
  "examples/cmd_drivers/convert_f32_to_bf16",
  "examples/cmd_drivers/search_memory_index",
  "examples/cmd_drivers/build_and_insert_delete_memory_index"
]
resolver = "2"

[profile.release]
opt-level = 3
codegen-units=1
