[package]
name = "vector-search-demo"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diskann = { path = "../../../diskann" }
diskann-vector = { path = "../../../vector" }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.128"

# Tracing ecosystem for logging and instrumentation
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }